### ISSUE TITLE
Please publish the complete flow

### ISSUE THREAD

**Issue by norbla** [phyunsj/node-red-dashboard-login#1]
Hi phyunsj,

the JSON-file just contains one node.
Can you please publish the hole flow?

TIA!

Kind regards,
norbla

**Comment by phyunsj** [comment]
My workspace is deleted. I noticed that I incorrectly cut & paste nodes. Sorry about that. I plan to re-create  JSON based on the flow diagram.

**Comment by phyunsj** [comment]
JSON-file is posted.
