### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by mralperem** [phyunsj/node-red-dashboard-login#2]
Hello,

I would like to ask you about the security of using this flow. How secure is to use this flow. I mean the passwords are not salted and everyone who can acsess the admin area can see the passwords. 

I am sorry about asking too much questions but I am trying to develop something rock solid and off course hacker / scammer prof so I would be really appriciated if you can help me out here. Thank you

**Comment by phyunsj** [comment]
Please review the following links 
https://nodered.org/docs/security
https://notenoughtech.com/home-automation/nodered-home-automation/nodered-security/
https://github.com/node-red/cookbook.nodered.org/wiki/How-to-safely-expose-Node-RED-to-the-Internet

Everyone has a different opinion & different requirement.

**Comment by mralperem** [comment]
I understand thank you. I have reviewed that pages but I would like to get your opinion.

**Comment by phyunsj** [comment]
I would follow the guideline provided by nodered.org. Then, measure if it meets the requirements (security risks/vulnerability) depending on the industry you belong to (or targeted market)  
 
For example, 
https://www.beyondsecurity.com/vulnerability_assessment_requirements_nerc-cip.html (This is well-summarized what NERC-CIP-00X is for). 

 Sorry that I can't give a clear answer.
