### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by baha00** [phyunsj/node-red-dashboard-login#3]
Hi, there, this is very innovative way of securing it, how is group set to hidden by default? 
Would this work with TABs as well like with groups?

**Comment by phyunsj** [comment]
Yes, it is possible. 

For example, 
If I have two tabs - "Dashboard" and "Another".  The following msg will be sent from "Sign-In-Redirection" function node. (I moved "History" group under "Another" tab.)

msg.payload = { group: {
    hide : ["Dashboard_SensorData",  "Another_History"],
    show : ["Dashboard_Signin"]
     },
     tab : 0, // Redirect to Dashboard tab automatically
};

You can find more info from ui_ui_control.js.
