### ISSUE TITLE
Logoff button

### ISSUE THREAD

**Issue by robertowiest** [phyunsj/node-red-dashboard-login#6]
hello, very good your flows, congratulations. I am using them in my streams but as I am new to this node-re environment I would like to know how I could implement a logoff button

**Comment by phyunsj** [comment]
Please create/add ui-button and connect to [sign-in redirection] function node. (you might want to clear a session beforehand)
Hope this helps.

**Comment by robertowiest** [comment]
Hello, very good. Worked perfectly. One more thing. How could I implement auto login with a specific user of the operating system itself. For example, if the logged in operating system user is root, then the system would automatically log in as admin user.

**Comment by phyunsj** [comment]
comment on the last question. In order to achieve your goal, I believe you need 3rd party provider (i..e, Okta single sign-on)
