### ISSUE TITLE
Disable Side Menu

### ISSUE THREAD

**Issue by robertowiest** [phyunsj/node-red-dashboard-login#7]
Hello, is it possible to disable the side menu only on the login screen? How could you do that?

![image](https://user-images.githubusercontent.com/15611961/64247735-d8b3b780-cee5-11e9-958e-b83e63acf092.png)

**Comment by phyunsj** [comment]
I don't think it is possible without changing node-red-dashboard itself. I didn't see any option to enable(or disable) the top [=] button once you created it from layout editor.

**Comment by robertowiest** [comment]
Hi, that's right. This would not be with the system but a dashboard functionality.
