### ISSUE TITLE
Hide/Show Flows 

### ISSUE THREAD

**Issue by robertowiest** [phyunsj/node-red-dashboard-login#8]
Hi, I'm using dashboard-login to control user access to my dash. I defined two user groups and am controlling as follows. However, if I login to the system with the admin user, for example, even putting hide in a specific flow, this same flow is displayed to the admin group user.
This is what I have coded in flow

![image](https://user-images.githubusercontent.com/15611961/64332535-21817400-cfab-11e9-9af9-4b221e2b0232.png)

```
if (userGroup === "admin") {
/* ui-control payload /
msg.payload = {
group: {
show : [
],
hide : [
"Home_Status_Linha_1"
]
}
};
} else {
/ ui-control payload */
msg.payload = {
group: {
show : [
"Linha_1"
],
hide : [
"Home_Status_Linha_1",
"Home_Sistema_Login"
]
}
};
}
```

**Comment by phyunsj** [comment]
Please add [Debug] node and examine the output (msg object) from a function node

**Comment by robertowiest** [comment]
Ok. I created flows with ui controls to accomplish what I want. Thank you.
